apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - compact/thanos-compact.yaml
  - query/thanos-query-deployment.yaml
  - query/thanos-query-service.yaml
  - query/thanos-query-serviceaccount.yaml
  - store/thanos-store-service.yaml
  - store/thanos-store-statefulset.yaml
  - thanos-objectstorage.yaml
