apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfogram-server.fullname" .}}
  labels:
    {{- include "portfogram-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
    - name: http-management
      port: 8081
      targetPort: http-management
      protocol: TCP
      nodePort: {{ .Values.service.managementNodePort }}
  selector:
    {{- include "portfogram-server.selectorLabels" . | nindent 4 }}
