apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-storegateway-1
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  storageClassName: standard
  volumeName: data-storegateway-1-pv