apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      slack_api_url_file: /etc/alertmanager/secrets/slack_api_url
      resolve_timeout: 5m

    route:
      receiver: 'slack-alerts'
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - match:
            severity: critical
          receiver: 'slack-critical'
          continue: true
        - match:
            severity: warning
          receiver: 'slack-warning'
          continue: true
        - match:
            team: backend
          receiver: 'slack-backend'
    
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'region']
    
    receivers:
      - name: 'slack-alerts'
        slack_configs:
          - channel: '#alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            footer: 'Alertmanager'
      
      - name: 'slack-critical'
        slack_configs:
          - channel: '#critical-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            footer: 'Alertmanager'

      - name: 'slack-warning'
        slack_configs:
          - channel: '#warning-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:warning:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            footer: 'Alertmanager'

      - name: 'slack-backend'
        slack_configs:
          - channel: '#backend-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:computer:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            footer: 'Alertmanager'

    templates:
      - '/etc/alertmanager/templates.tmpl'

  templates.tmpl: |
    {{/* Severity of the alert */}}
    {{ define "__alert_severity" -}}
        {{- if eq .CommonLabels.severity "critical" -}}
        *Severity:* :red_circle: `Critical`
        {{- else if eq .CommonLabels.severity "warning" -}}
        *Severity:* :warning: `Warning`
        {{- else if eq .CommonLabels.severity "info" -}}
        *Severity:* :information_source: `Info`
        {{- else -}}
        *Severity:* :question: `{{ .CommonLabels.severity }}`
        {{- end }}
    {{- end }}

    {{/* Title of the Slack alert */}}
    {{ define "slack.title" -}}
      {{ if eq .Status "firing" }}:rotating_light:{{ else }}:green_heart:{{ end }} {{ .Status | toUpper }}{{ if eq .Status "firing" }} ({{ .Alerts.Firing | len }}){{ end }}: {{ .CommonLabels.alertname }}
    {{- end }}

    {{/* Color of Slack attachment */}}
    {{ define "slack.color" -}}
        {{ if eq .Status "firing" -}}
            {{ if eq .CommonLabels.severity "warning" -}}
                #FFA500
            {{- else if eq .CommonLabels.severity "critical" -}}
                #FF0000
            {{- else -}}
                #439FE0
            {{- end -}}
        {{ else -}}
        #36a64f
        {{- end }}
    {{- end }}

    {{/* The text to display in the alert */}}
    {{ define "slack.text" -}}
        {{ template "__alert_severity" . }}
        {{- if (index .Alerts 0).Annotations.summary }}
        *Summary:* {{ (index .Alerts 0).Annotations.summary }}
        {{- end }}

        {{ range .Alerts }}
        ---
        {{- if .Annotations.description }}
        *Description:* {{ .Annotations.description }}
        {{- end }}
        {{- if .Annotations.message }}
        *Message:* {{ .Annotations.message }}
        {{- end }}
        *Labels:*
        {{- range .Labels.SortedPairs }}
        • *{{ .Name }}:* `{{ .Value }}`
        {{- end }}
        {{- if .Annotations.runbook_url }}
        *Runbook:* {{ .Annotations.runbook_url }}
        {{- end }}
        {{- if .Annotations.grafana_url }}
        *Dashboard:* {{ .Annotations.grafana_url }}
        {{- end }}
        {{- end }}

        *Job:* `{{ .CommonLabels.job }}`
        *Alert Source:* `{{ .CommonLabels.alertname }}`
    {{- end }}