alertmanager:
  configMap: alertmanager
  configMapOverrideName: alertmanager-config
  config: {}  # 이 부분을 비워두고 ConfigMap을 사용하도록 합니다.
  configSecret: alertmanager-secrets
  extraSecretMounts:
    - name: alertmanager-secrets
      secretName: alertmanager-secrets
      mountPath: /etc/alertmanager/secrets
      readOnly: true