apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: observability
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093       # 서비스에서 노출할 포트
      targetPort: 9093 # alertmanager 컨테이너에서 사용하는 포트
      nodePort: 30093  # 클러스터 외부에서 접근할 NodePort (자동으로 설정 가능)
