alertmanager:
  configMap: alertmanager-config
  configMapOverrideName: alertmanager-config
  config: {}
  configSecret: alertmanager-secrets
  extraSecretMounts:
    - name: alertmanager-secrets
      secretName: alertmanager-secrets
      mountPath: /etc/alertmanager/secrets
      readOnly: true
  extraConfigmapMounts:
    - name: alertmanager-config
      mountPath: /etc/alertmanager
      configMap: alertmanager-config
      readOnly: true