# alertmanager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
          ports:
            - containerPort: 9093
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: alertmanager-secrets
              mountPath: /etc/alertmanager/secrets
              readOnly: true
            - name: storage-volume
              mountPath: /alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
        - name: alertmanager-secrets
          secret:
            secretName: alertmanager-secrets
        - name: storage-volume
          emptyDir: {}
---
# alertmanager-sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-secrets
  namespace: observability
spec:
  encryptedData:
    slack_api_url: AgB3CihRGyIaKm61GbBhKQesxjkMmOhP3rvv95re+vLdOZmN6qxXQlTTZdDBZ+nFasbuG0sMs/3N8eOLjkHP8pLHp8SpbWiixQSy86QTxjky3hehNpq94lRa9g6TMrCiBrZUrexOd9EIPfk4eAgjMDXHvUJb8fsSqpCi+YWPrZ+g9CzmoKRTUb2yhH5Uw7gdbXOtbLo2kAdTr7hYVieueDxk+AX+mRWk9m5VQSEWv1Fo8DpEO9ovIwOT3eHHvXBQQfgf4Ia7OiUdz1a+/h8aBn96qy213LW5UmP8gOtrJxZCifjfqCRnAR8hfzNAUFIpj6CdIRMEbFsXOcuYWgTqbD0R6RAabLB9o1aWEBCYgWwycb0kyH+VKWhIT0Q3Q3FGv5wPiViY0asauAPctuXJcGByRl7H0jPd98MyQwPcZy1ShsuSEbde/2E0n2tMObhOl/h+e8q9kcv/DjtZUDFeykzPGDQfQkl61DJEXxz6/svoMSYQV/wfx15MXZsP+Kwxjk2LUmBGI0qUp8gsaBbK7sZh4VSkN6GRuxmRNPlS3ukV2U7JiB1Xaoc4/Z+QB4MtrXb2WHY0fhoqoCZLtytx8qUnfCJ4gaGpboWZulkZiMupvuezvY8joH5vI2w0elw9DUicB+y+d+xkMWsLJdHaJj+GVgzvz4n/ifaYpNCh+mAnhZtCsX9+Kf9AZJh5pZcw2jbNViG5KcL8TBWs4Etfxe+GZiXNydIawSrUsY5Uk6Dp04adin1OPR749EBG7IpFNdBHrhJoe5aZ20oVQL8D5RPXEvZWiu1VUBteqv3XvS28gRw=