alertmanager:
  configMap: alertmanager-config
  configMapOverrideName: alertmanager-config
  configSecret: alertmanager-secrets
  extraSecretMounts:
    - name: alertmanager-secrets
      secretName: alertmanager-secrets
      mountPath: /etc/alertmanager/secrets
      readOnly: true

  # volumes와 volumeMounts를 alertmanager 섹션 내부로 이동
  extraVolumes:
    - name: secrets
      secret:
        secretName: alertmanager-secrets
    - name: config
      configMap:
        name: alertmanager-config

  extraVolumeMounts:
    - name: secrets
      mountPath: /etc/alertmanager/secrets
      readOnly: true

    - name: config
      mountPath: /etc/alertmanager
      subPath: alertmanager.yml



  # Alertmanager 컨테이너의 arguments를 오버라이드
  extraArgs:
    - "--config.file=/etc/alertmanager/alertmanager.yml"