apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: observability
spec:
  type: LoadBalancer
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093       # 서비스에서 노출할 포트
      targetPort: 9093