#alertmanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'slack-alerts'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - match:
            severity: critical
          receiver: 'slack-critical'
        - match:
            severity: warning
          receiver: 'slack-warning'
        - match:
            team: backend
          receiver: 'slack-backend'
        - match:
            team: infra
          receiver: 'slack-infra'

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']
    
    receivers:
      - name: 'slack-critical'
        slack_configs:
          - api_url: 'https://slack.com/api/chat.postMessage'
            channel: '#critical-alerts'
            send_resolved: true
            http_config:
              authorization:
                type: Bearer
                credentials_file: /etc/alertmanager/secrets/slack_token
      
      - name: 'slack-warning'
        slack_configs:
          - api_url: 'https://slack.com/api/chat.postMessage'
            channel: '#warning-alerts'
            send_resolved: true
            http_config:
              authorization:
                type: Bearer
                credentials_file: /etc/alertmanager/secrets/slack_token
      
      - name: 'slack-backend'
        slack_configs:
          - api_url: 'https://slack.com/api/chat.postMessage'
            channel: '#backend-alerts'
            send_resolved: true
            http_config:
              authorization:
                type: Bearer
                credentials_file: /etc/alertmanager/secrets/slack_token

      - name: 'slack-infra'
        slack_configs:
          - api_url: 'https://slack.com/api/chat.postMessage'
            channel: '#infra-alerts'
            send_resolved: true
            http_config:
              authorization:
                type: Bearer
                credentials_file: /etc/alertmanager/secrets/slack_token
      
      - name: 'slack-alerts'
        slack_configs:
          - api_url: 'https://slack.com/api/chat.postMessage'
            channel: '#alerts'
            send_resolved: true
            http_config:
              authorization:
                type: Bearer
                credentials_file: /etc/alertmanager/secrets/slack_token
    
    templates:
      - '/etc/alertmanager/template/*.tmpl'
  template.tmpl: |
    {{ define "slack.default.title" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }} - {{ .GroupLabels.job }}
    {{ end }}
    
    {{ define "slack.default.text" }}
    :{{ if eq .Status "firing" }}warning{{ else }}white_check_mark{{ end }}: *{{ .Status | toUpper }}*: {{ .GroupLabels.alertname }}
    *Job:* {{ .GroupLabels.job }}
    *Severity:* {{ .CommonLabels.severity }}
    *Team:* {{ .CommonLabels.team }}
    
    {{ if .CommonAnnotations.summary }}*Summary:* {{ .CommonAnnotations.summary }}{{ end }}
    {{ if .CommonAnnotations.description }}*Description:* {{ .CommonAnnotations.description }}{{ end }}
    
    {{ if gt (len .Alerts.Firing) 0 }}
    *Alerts Firing:*
    {{ range .Alerts.Firing }}
      • {{ .Labels.instance }}: {{ .Annotations.description }}
    {{ end }}
    {{ end }}
    
    {{ if gt (len .Alerts.Resolved) 0 }}
    *Alerts Resolved:*
    {{ range .Alerts.Resolved }}
      • {{ .Labels.instance }}: {{ .Annotations.description }}
    {{ end }}
    {{ end }}
    
    {{ if .CommonAnnotations.runbook_url }}*Runbook:* {{ .CommonAnnotations.runbook_url }}{{ end }}
    {{ if .CommonAnnotations.dashboard_url }}*Dashboard:* {{ .CommonAnnotations.dashboard_url }}{{ end }}
    {{ end }}
