apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: observability
  labels:
    app: alertmanager
spec:
    replicas: 1
    selector:
      matchLabels:
        app: alertmanager
    template:
        metadata:
          labels:
            app: alertmanager
        spec:
          containers:
            - name: alertmanager
              image: prom/alertmanager:latest
              args:
                - "--config.file=/etc/alertmanager/alertmanager.yml"
                - "--storage.path=/alertmanager"
                - "--web.external-url=http://localhost:9093"
              ports:
                - containerPort: 9093
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/alertmanager
                - name: storage-volume
                  mountPath: /alertmanager
          volumes:
            - name: config-volume
              configMap:
                  name: alertmanager-config
            - name: storage-volume
              emptyDir: {}