apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      slack_api_url_file: /etc/alertmanager/secrets/slack_api_url
      resolve_timeout: 5m

    route:
      receiver: 'slack-alerts' # Default receiver
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - match:
            severity: critical
          receiver: 'slack-critical'
          continue: true
        - match:
            severity: warning  # 수정: 'waring'에서 'warning'으로 변경
          receiver: 'slack-warning'
          continue: true
        - match:
            team: backend
          receiver: 'slack-backend'
    
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'region']
    
    receivers:
      - name: 'slack-alerts'
        slack_configs:
          - channel: '#alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:ok:{{ end }}'
            color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            actions:
              - type: button
                text: 'Runbook :green_book:'
                url: '{{ .CommonAnnotations.runbook_url }}'
              - type: button
                text: 'Grafana'
                url: '{{ .CommonAnnotations.grafana_url }}'
              - type: button
                text: 'Silence :no_bell:'
                url: '{{ .ExternalURL }}/#/silences'
      
      - name: 'slack-critical'
        slack_configs:
          - channel: '#critical-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:ok:{{ end }}'
            color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
      - name: 'slack-warning'
        slack_configs:
          - channel: '#warning-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:warning:{{ else }}:ok:{{ end }}'
            color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
      - name: 'slack-backend'
        slack_configs:
          - channel: '#backend-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:computer:{{ else }}:ok:{{ end }}'
            color: '{{ if eq .Status "firing" }}#ADD8E6{{ else }}good{{ end }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

  template.tmpl: |
    {{ define "slack.title" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }}
    {{ end }}
    
    {{ define "slack.text" }}
    {{ if eq .Status "firing" }}:fire_engine:{{ else }}:green_heart:{{ end }} *{{ .Status | toUpper }}*: {{ .GroupLabels.alertname }}
    {{ .CommonAnnotations.summary }}
    
    *Description:* {{ .CommonAnnotations.description }}
    *Severity:* {{ .CommonLabels.severity }}
    *Job:* {{ .CommonLabels.job }}
    
    {{ if gt (len .Alerts.Firing) 0 }}
    *Alerts Firing:*
    {{ range .Alerts.Firing }}
      • {{ .Annotations.description }}
    {{ end }}
    {{ end }}
    
    {{ if gt (len .Alerts.Resolved) 0 }}
    *Alerts Resolved:*
    {{ range .Alerts.Resolved }}
      • {{ .Annotations.description }}
    {{ end }}
    {{ end }}
    
    *Runbook:* {{ .CommonAnnotations.runbook_url }}
    *Grafana:* {{ .CommonAnnotations.grafana_url }}
    {{ end }}