# alertmanager-sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-secrets
  namespace: observability
spec:
  encryptedData:
    slack_api_url: AgA2eqqZaoZgfqCK8/gPkcVzw0Lxgq84I4wgKkt2COQ+G3KEwg/SNMt71YEylzRWR7kwNbk0jQ0W97mpQxWtiuS4ZPuYUN5ILNnDvE2rin2NqNT3RrjK+qGZEcVeMVEnBqVPYro7o/3yJKL9XOVt68jevZLN58FsJJoXqswhBh8C6DN4XMBBKxo5tyV1vTDLgPDhjTzErQah06LJDiaHTobYzXXaKXPJGNm1336LGXlAM6MxR6syWfNBOnYBKpa1+qVmTVQ52k8iVYXIN9YkgNNCdWGLpp+jmzOj3auiRvu/uTnbBbLwRZ4CAjHKLj/JQKjAwT9RaxUGoj/4naPJQQlJt0DacyAXJ26wxl++zCqTWkwEv9+LHK5kwpxnBWf4YfalgS+IDcmkXeixnGbgcfDc7aUd5nQSYwa98AEaSwCQfwBmRMwvrAswjgSusvny5Lf5MaV/3eRNGIX81kyOrCKvF13m08Nq0m7dGCKA+RIz0NKzfeJCbHotMfncYCFFuRVOMhRm0kjN2piEVG6clA0XdRszgQ78bcEbWTE4+0vVZQpWom7RFkPL322wsVyTQ4j7U/HOGuLcpqf1bbxBxioBXTTi/9jo12LNzfkx7Ihtwaclt7L4n9iBW5Ev+8DJOlOkemVWyVyQje1kAmZ7hAh0V26rB1vFt6CspB7y20GenEeVU9Yy4fnVgVHCSA1VeLVyiHX116yuEnFmZYg0aSZB1pJ3LeaX6VRR7w8htuGSw/99VaTZ9zUUr1QgtW7L61NpOaRTxarlB+IDiwV/W1zj1SXlCipDUmPTLBbZO3zvUi8=
