apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: observability
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093