apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      slack_api_url_file: /etc/alertmanager/secrets/slack_api_url
      resolve_timeout: 5m

    route:
      receiver: 'slack-alerts'
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - match:
            severity: critical
          receiver: 'slack-critical'
          continue: true
        - match:
            severity: warning
          receiver: 'slack-warning'
          continue: true
        - match:
            team: backend
          receiver: 'slack-backend'
    
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'region']
    
    receivers:
      - name: 'slack-alerts'
        slack_configs:
          - channel: '#alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: '{{ template "slack.text" . }}'
              - type: actions
                elements:
                  - type: button
                    text:
                      type: plain_text
                      text: 'Runbook :green_book:'
                    url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
                  - type: button
                    text:
                      type: plain_text
                      text: 'Grafana :grafana:'
                    url: '{{ (index .Alerts 0).Annotations.grafana_url }}'
                  - type: button
                    text:
                      type: plain_text
                      text: 'Silence :no_bell:'
                    url: '{{ template "__alert_silence_link" . }}'
      
      - name: 'slack-critical'
        slack_configs:
          - channel: '#critical-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: '{{ template "slack.text" . }}'
              - type: actions
                elements:
                  - type: button
                    text:
                      type: plain_text
                      text: 'Runbook :green_book:'
                    url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
                  - type: button
                    text:
                      type: plain_text
                      text: 'Grafana :grafana:'
                    url: '{{ (index .Alerts 0).Annotations.grafana_url }}'
                  - type: button
                    text:
                      type: plain_text
                      text: 'Silence :no_bell:'
                    url: '{{ template "__alert_silence_link" . }}'

      - name: 'slack-warning'
        slack_configs:
          - channel: '#warning-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:warning:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: '{{ template "slack.text" . }}'
              - type: actions
                elements:
                  - type: button
                    text:
                      type: plain_text
                      text: 'Runbook :green_book:'
                    url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
                  - type: button
                    text:
                      type: plain_text
                      text: 'Grafana :grafana:'
                    url: '{{ (index .Alerts 0).Annotations.grafana_url }}'
                  - type: button
                    text:
                      type: plain_text
                      text: 'Silence :no_bell:'
                    url: '{{ template "__alert_silence_link" . }}'

      - name: 'slack-backend'
        slack_configs:
          - channel: '#backend-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:computer:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: '{{ template "slack.text" . }}'
              - type: actions
                elements:
                  - type: button
                    text:
                      type: plain_text
                      text: 'Runbook :green_book:'
                    url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
                  - type: button
                    text:
                      type: plain_text
                      text: 'Grafana :grafana:'
                    url: '{{ (index .Alerts 0).Annotations.grafana_url }}'
                  - type: button
                    text:
                      type: plain_text
                      text: 'Silence :no_bell:'
                    url: '{{ template "__alert_silence_link" . }}'

    templates:
      - '/etc/alertmanager/templates.tmpl'

  templates.tmpl: |
    {{/* Alertmanager Silence link */}}
    {{ define "__alert_silence_link" -}}
        {{ .ExternalURL }}/#/silences/new?filter=%7B
        {{- range .CommonLabels.SortedPairs -}}
            {{- if ne .Name "alertname" -}}
                {{- .Name }}%3D"{{- .Value -}}"%2C%20
            {{- end -}}
        {{- end -}}
        alertname%3D"{{- .CommonLabels.alertname -}}"%7D
    {{- end }}

    {{/* Severity of the alert */}}
    {{ define "__alert_severity" -}}
        {{- if eq .CommonLabels.severity "critical" -}}
        *Severity:* `Critical`
        {{- else if eq .CommonLabels.severity "warning" -}}
        *Severity:* `Warning`
        {{- else if eq .CommonLabels.severity "info" -}}
        *Severity:* `Info`
        {{- else -}}
        *Severity:* :question: {{ .CommonLabels.severity }}
        {{- end }}
    {{- end }}

    {{/* Title of the Slack alert */}}
    {{ define "slack.title" -}}
      [{{ .Status | toUpper -}}
      {{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end -}}
      ] {{ .CommonLabels.alertname }}
    {{- end }}

    {{/* Color of Slack attachment (appears as line next to alert )*/}}
    {{ define "slack.color" -}}
        {{ if eq .Status "firing" -}}
            {{ if eq .CommonLabels.severity "warning" -}}
                warning
            {{- else if eq .CommonLabels.severity "critical" -}}
                danger
            {{- else -}}
                #439FE0
            {{- end -}}
        {{ else -}}
        good
        {{- end }}
    {{- end }}

    {{/* The text to display in the alert */}}
    {{ define "slack.text" -}}
        {{ template "__alert_severity" . }}
        {{- if (index .Alerts 0).Annotations.summary }}
        {{- "\n" -}}
        *Summary:* {{ (index .Alerts 0).Annotations.summary }}
        {{- end }}

        {{ range .Alerts }}
            {{- if .Annotations.description }}
            {{- "\n" -}}
            {{ .Annotations.description }}
            {{- "\n" -}}
            {{- end }}
            {{- if .Annotations.message }}
            {{- "\n" -}}
            {{ .Annotations.message }}
            {{- "\n" -}}
            {{- end }}
        {{- end }}
    {{- end }}