apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    # (이전 alertmanager.yml 내용은 그대로 유지)

  templates.tmpl: |
    {{/* Severity of the alert */}}
    {{ define "__alert_severity" -}}
        {{- if eq .CommonLabels.severity "critical" -}}
        *Severity:* :red_circle: `Critical`
        {{- else if eq .CommonLabels.severity "warning" -}}
        *Severity:* :warning: `Warning`
        {{- else if eq .CommonLabels.severity "info" -}}
        *Severity:* :information_source: `Info`
        {{- else -}}
        *Severity:* :question: `{{ .CommonLabels.severity }}`
        {{- end }}
    {{- end }}

    {{/* Title of the Slack alert */}}
    {{ define "slack.title" -}}
      {{ if eq .Status "firing" }}:rotating_light:{{ else }}:green_heart:{{ end }} {{ .Status | toUpper }}{{ if eq .Status "firing" }} ({{ .Alerts.Firing | len }}){{ end }}: {{ .CommonLabels.alertname }}
    {{- end }}

    {{/* Color of Slack attachment */}}
    {{ define "slack.color" -}}
        {{ if eq .Status "firing" -}}
            {{ if eq .CommonLabels.severity "warning" -}}
                #FFA500
            {{- else if eq .CommonLabels.severity "critical" -}}
                #FF0000
            {{- else -}}
                #439FE0
            {{- end -}}
        {{ else -}}
        #36a64f
        {{- end }}
    {{- end }}

    {{/* The text to display in the alert */}}
    {{ define "slack.text" -}}
        {{ template "__alert_severity" . }}
        {{- if (index .Alerts 0).Annotations.summary }}
        *Summary:* {{ (index .Alerts 0).Annotations.summary }}
        {{- end }}

        {{ range .Alerts }}
        ---
        {{- if .Annotations.description }}
        *Description:* {{ .Annotations.description }}
        {{- end }}
        {{- if .Annotations.message }}
        *Message:* {{ .Annotations.message }}
        {{- end }}
        *Labels:*
        {{- range .Labels.SortedPairs }}
        • *{{ .Name }}:* `{{ .Value }}`
        {{- end }}
        {{- if .Annotations.runbook_url }}
        *Runbook:* {{ .Annotations.runbook_url }}
        {{- end }}
        {{- if .Annotations.grafana_url }}
        *Dashboard:* {{ .Annotations.grafana_url }}
        {{- end }}
        {{- end }}

        *Job:* `{{ .CommonLabels.job }}`
        *Alert Source:* `{{ .CommonLabels.alertname }}`
    {{- end }}