#alertmanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
# slack_uri의 경우 git에 노출되게 되면, 자동으로 SLack측에서 이걸 위험으로 감지하고 해당 uri를 무효화시킴
  # 그래서 slack-uri의 경우 Sealed-secret 이용해서 처리함 -> 미디움에 정리
  alertmanager.yml: |
    global:
      slack_api_url_file: /etc/alertmanager/secrets/slack_api_url

    route:
      receiver: 'slack-alerts' # Default receiver
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - match:
            severity: critical
          receiver: 'slack-critical'
          continue: true
        - match:
           severity: waring
          receiver: 'slack-warning'
          continue: true
        - match:
            team: backend
          receiver: 'slack-backend'
          
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'job']
        
    receivers:
      - name: 'slack-alerts'
        slack_configs:
          - channel: '#alerts'
            send_resolved: true
      - name: 'slack-critical'
        slack_configs:
          - channel: '#critical-alerts'
            send_resolved: true
      - name: 'slack-warning' 
        slack_configs:
          - channel: '#warning-alerts'
            send_resolved: true
      - name: 'slack-backend'
        slack_configs:
          - channel: '#backend-alerts'
            send_resolved: true

    templates:
      - '/etc/alertmanager/template.tmpl'
  template.tmpl: |
    {{ define "slack.default.title" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }}
    {{ end }}
    
    {{ define "slack.default.text" }}
    :{{ if eq .Status "firing" }}fire_engine{{ else }}green_heart{{ end }}: *{{ .Status | toUpper }}*: {{ .GroupLabels.alertname }}
    {{ .CommonAnnotations.summary }}
    
    *Description:* {{ .CommonAnnotations.description }}
    *Severity:* {{ .CommonLabels.severity }}
    *Job:* {{ .CommonLabels.job }}
    
    {{ if gt (len .Alerts.Firing) 0 }}
    *Alerts Firing:*
    {{ range .Alerts.Firing }}
      • {{ .Annotations.description }}
    {{ end }}
    {{ end }}
    
    {{ if gt (len .Alerts.Resolved) 0 }}
    *Alerts Resolved:*
    {{ range .Alerts.Resolved }}
      • {{ .Annotations.description }}
    {{ end }}
    {{ end }}
    
    *Runbook:* {{ .CommonAnnotations.runbook_url }}
    *Grafana:* {{ .CommonAnnotations.grafana_url }}
    {{ end }}      
      
      
