config:
  global:
    slack_api_url: 'https://hooks.slack.com/services/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'
  route:
    receiver: 'slack-notifications'
    group_by: ['alertname', 'instance', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h

    routes:
      - match:
          severity: critical
        receiver: 'slack-critical'
      - match:
          severity: warning
        receiver: 'slack-warnings'

  receivers:
    - name: 'slack-notifications'
      slack_configs:
          - api_url: 'https://hooks.slack.com/services/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'
            channel: '#alerts'
            send_resolved: true
    - name: 'slack-critical'
      slack_configs:
        - channel: '#alerts-critical'
          send_resolved: true
          icon_emoji: ':red_circle:'
          title: "[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"
          text: |
            *Alert:* {{ .GroupLabels.alertname }}
            *Severity:* {{ .CommonLabels.severity }}
            *Instance:* {{ .GroupLabels.instance }}
            
            *Summary:* {{ (index .Alerts 0).Annotations.summary }}
            *Description:* {{ (index .Alerts 0).Annotations.description }}
            
            {{ if gt (len .Alerts) 1 }}
            *Additional Alerts:*
            {{ range $index, $alert := (slice .Alerts 1) }}
            {{ $index | add1 }}. {{ $alert.Annotations.summary }}
            {{ end }}
            {{ end }}

    - name: 'slack-warnings'
      slack_configs:
        - channel: '#alerts-warnings'
          send_resolved: true
          icon_emoji: ':warning:'
          title: "[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"
          text: |
            *Alert:* {{ .GroupLabels.alertname }}
            *Severity:* {{ .CommonLabels.severity }}
            *Instance:* {{ .GroupLabels.instance }}
            
            *Summary:* {{ (index .Alerts 0).Annotations.summary }}
            *Description:* {{ (index .Alerts 0).Annotations.description }}
