apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
  namespace: observability
type: Opaque
stringData:
  slack_api_url: "https://hooks.slack.com/services/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"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'slack-notifications'
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - match:
            severity: critical
          receiver: 'slack-critical'
        - match:
            severity: warning
          receiver: 'slack-warnings'

    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - api_url: '{{ .SlackAPIURL }}'
            channel: '#alerts'
            send_resolved: true
            title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
            text: |
              *Alert:* {{ .GroupLabels.alertname }}
              *Severity:* {{ .CommonLabels.severity }}
              *Summary:* {{ (index .Alerts 0).Annotations.summary }}
              *Description:* {{ (index .Alerts 0).Annotations.description }}
              {{ if (index .Alerts 0).Annotations.dashboard_url }}
              *Dashboard:* {{ (index .Alerts 0).Annotations.dashboard_url }}
              {{ end }}
              {{ if (index .Alerts 0).Annotations.pod_logs_url }}
              *Pod Logs:* {{ (index .Alerts 0).Annotations.pod_logs_url }}
              {{ end }}

      - name: 'slack-critical'
        slack_configs:
          - api_url: '{{ .SlackAPIURL }}'
            channel: '#alerts-critical'
            send_resolved: true
            icon_emoji: ':red_circle:'
            title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
            text: |
              *Alert:* {{ .GroupLabels.alertname }}
              *Severity:* {{ .CommonLabels.severity }}
              *Summary:* {{ (index .Alerts 0).Annotations.summary }}
              *Description:* {{ (index .Alerts 0).Annotations.description }}
              {{ if (index .Alerts 0).Annotations.dashboard_url }}
              *Dashboard:* {{ (index .Alerts 0).Annotations.dashboard_url }}
              {{ end }}
              {{ if (index .Alerts 0).Annotations.pod_logs_url }}
              *Pod Logs:* {{ (index .Alerts 0).Annotations.pod_logs_url }}
              {{ end }}

      - name: 'slack-warnings'
        slack_configs:
          - api_url: '{{ .SlackAPIURL }}'
            channel: '#alerts-warnings'
            send_resolved: true
            icon_emoji: ':warning:'
            title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
            text: |
              *Alert:* {{ .GroupLabels.alertname }}
              *Severity:* {{ .CommonLabels.severity }}
              *Summary:* {{ (index .Alerts 0).Annotations.summary }}
              *Description:* {{ (index .Alerts 0).Annotations.description }}
              {{ if (index .Alerts 0).Annotations.dashboard_url }}
              *Dashboard:* {{ (index .Alerts 0).Annotations.dashboard_url }}
              {{ end }}
              {{ if (index .Alerts 0).Annotations.pod_logs_url }}
              *Pod Logs:* {{ (index .Alerts 0).Annotations.pod_logs_url }}
              {{ end }}

    templates:
      - '/etc/alertmanager/*.tmpl'