apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      slack_api_url_file: /etc/alertmanager/secrets/slack_api_url
      resolve_timeout: 5m

    route:
      receiver: 'slack-alerts'
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - match:
            severity: critical
          receiver: 'slack-critical'
          continue: true
        - match:
            severity: warning
          receiver: 'slack-warning'
          continue: true
        - match:
            team: backend
          receiver: 'slack-backend'
    
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'region']
    
    receivers:
      - name: 'slack-alerts'
        slack_configs:
          - channel: '#alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            footer: 'PortfoGram Alertmanager | <{{ template "slack.runbook" . }}|View Runbook>'

      - name: 'slack-critical'
        slack_configs:
          - channel: '#critical-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:fire:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            footer: 'PortfoGram Alertmanager'

      - name: 'slack-warning'
        slack_configs:
          - channel: '#warning-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:warning:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            footer: 'PortfoGram Alertmanager'

      - name: 'slack-backend'
        slack_configs:
          - channel: '#backend-alerts'
            send_resolved: true
            icon_emoji: '{{ if eq .Status "firing" }}:computer:{{ else }}:ok:{{ end }}'
            color: '{{ template "slack.color" . }}'
            title: '{{ template "slack.title" . }}'
            text: '{{ template "slack.text" . }}'
            footer: 'PortfoGram Alertmanager'

    templates:
      - '/etc/alertmanager/templates.tmpl'

  templates.tmpl: |
    {{/* Color of Slack attachment */}}
    {{ define "slack.color" -}}
        {{- if eq .Status "firing" -}}
            {{- if eq .CommonLabels.severity "critical" -}}
                #FF0000
            {{- else if eq .CommonLabels.severity "warning" -}}
                #FFA500
            {{- else -}}
                #0000FF
            {{- end -}}
        {{- else -}}
            #00FF00
        {{- end }}
    {{- end }}

    {{/* Title of the Slack alert */}}
    {{ define "slack.title" -}}
        {{- if eq .Status "firing" -}}🚨 ALERT FIRING
        {{- else -}}✅ ALERT RESOLVED
        {{- end -}}
        : {{ .CommonLabels.alertname }}
    {{- end }}

    {{ define "slack.text" }}
    *Alert:* `{{ .CommonLabels.alertname }}`
    *Severity:* `{{ .CommonLabels.severity | toUpper }}`
    *Summary:* {{ (index .Alerts 0).Annotations.summary }}
    *Affected Instances:* {{ .Alerts | len }}

    *Key Details:*
    • *Cluster:* `{{ (index .Alerts 0).Labels.cluster }}`
    • *Namespace:* `{{ (index .Alerts 0).Labels.kubernetes_namespace }}`
    • *Pod:* `{{ (index .Alerts 0).Labels.kubernetes_pod_name }}`
    • *Reason:* `{{ (index .Alerts 0).Labels.reason }}`

    *Actions:*
    • <{{ (index .Alerts 0).GeneratorURL }}|View in Prometheus>
    • <https://your-alertmanager-url.com/#/silences/new?filter=%7balertname%3D%22{{ .CommonLabels.alertname }}%22%7d|Silence Alert>
    
    *Detailed Information:*
    {{ range .Alerts }}
    ──────────────────────
    • *Resource:* `{{ .Labels.kubernetes_pod_name | default .Labels.instance }}`
    {{- if .Labels.container }}
    • *Container:* `{{ .Labels.container }}`
    {{- end }}
    • *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
    {{- if .Labels.reason }}
    • *Reason:* `{{ .Labels.reason }}`
    {{- end }}
    {{- range .Labels.SortedPairs }}
    {{- if and (ne .Name "alertname") (ne .Name "severity") (ne .Name "cluster") (ne .Name "kubernetes_namespace") (ne .Name "job") (ne .Name "instance") (ne .Name "kubernetes_pod_name") (ne .Name "container") (ne .Name "reason") }}
    • *{{ .Name }}:* `{{ .Value }}`
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{ end }}

    {{/* Runbook URL */}}
    {{ define "slack.runbook" -}}
        {{- if (index .Alerts 0).Annotations.runbook_url -}}
            {{- (index .Alerts 0).Annotations.runbook_url -}}
        {{- else -}}
            https://wiki.portfogram.com/runbooks
        {{- end -}}
    {{- end }}