apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-deployment.yaml
  - prometheus-service-monitor.yaml
  - thanos-sidecar-configmap.yaml
  - prometheus-configmap.yaml
  - prometheus-rbac.yaml
  - alertmanager-sealed-secret.yaml
  - alertmanager-config.yaml

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: observability
    valuesFile: values.yaml
    version: 25.23.0
    includeCRDs: false

  - name: alertmanager
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: alertmanager
    namespace: observability
    valuesFile: alertmanager-values.yaml
    version: 0.27.0
    includeCRDs: false

helmGlobals:
  chartHome: charts

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: alertmanager
      namespace: observability
    spec:
      template:
        spec:
          containers:
            - name: alertmanager
              volumeMounts:
                - name: config
                  mountPath: /etc/alertmanager
                - name: alertmanager-secrets
                  mountPath: /etc/alertmanager/secrets
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: alertmanager-config
            - name: alertmanager-secrets
              secret:
                secretName: alertmanager-secrets