apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-deployment.yaml
  - prometheus-service-monitor.yaml
  - thanos-sidecar-configmap.yaml
  - prometheus-configmap.yaml
  - prometheus-rbac.yaml
  - alertmanager-sealed-secret.yaml
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml


helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: observability
    valuesFile: values.yaml
    version: 25.23.0
    includeCRDs: false


helmGlobals:
  chartHome: charts