apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: observability
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: http
      interval: 15s