# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'asia-southeast1'
        replica: '$(POD_NAME)'
    
    rule_files:
      - /etc/prometheus/rules.yml

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager.observability.svc.cluster.local:9093
          api_version: v2

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node'
        static_configs:
          - targets: ['localhost:9100']
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
            
            
  rules.yml: |
    groups:
      - name: example
        rules:
        - alert: AlwaysFiring
          expr: vector(1)
          labels:
            severity: critical
          annotations:
            summary: This alert is always firing
            description: This is a test alert that is always firing
  
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: warning
            team: infrastructure
          annotations:
            summary: High CPU usage detected
            description: CPU usage is above 80% on {{ $labels.instance }}
  
      - name: kubernetes-system-alerts
        rules:
        - alert: EKSNodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "EKS 노드 {{ $labels.node }} Ready 상태 아님"
            description: "EKS 노드 {{ $labels.node }}가 5분 이상 Ready 상태가 아닙니다. AWS 콘솔에서 노드 상태를 확인하세요."
  
        - alert: OTelCollectorHighCPUUsage
          expr: rate(process_cpu_seconds_total{job="otel-collector"}[5m]) > 0.8
          for: 10m
          labels:
            severity: warning
            team: observability
          annotations:
            summary: "OpenTelemetry Collector CPU 사용량 높음"
            description: "OpenTelemetry Collector의 CPU 사용량이 10분 동안 80%를 초과했습니다. 수집기 구성을 최적화하거나 리소스를 늘리는 것을 고려하세요."
  
        - alert: LokiHighQueryLatency
          expr: histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket{route="/loki/api/v1/query_range"}[5m])) by (le)) > 10
          for: 15m
          labels:
            severity: warning
            team: observability
          annotations:
            summary: "Loki 쿼리 지연 시간 높음"
            description: "Loki 쿼리의 99번째 백분위 지연 시간이 15분 동안 10초를 초과했습니다. 로그 쿼리 최적화가 필요할 수 있습니다."
  
        - alert: RedisHighMemoryUsage
          expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
          for: 15m
          labels:
            severity: warning
            team: database
          annotations:
            summary: "Redis 메모리 사용량 높음"
            description: "Redis 인스턴스의 메모리 사용량이 15분 동안 90%를 초과했습니다. 캐시 정책을 검토하거나 메모리를 증설하세요."
  
        - alert: EKSPodPending
          expr: sum(kube_pod_status_phase{phase="Pending"}) > 5
          for: 10m
          labels:
            severity: warning
            team: infrastructure
          annotations:
            summary: "다수의 EKS Pod Pending 상태"
            description: "10분 이상 5개 이상의 Pod가 Pending 상태입니다. EKS 노드 용량을 확인하고 필요시 Auto Scaling 설정을 조정하세요."
  
        - alert: HighErrorRatePortfolioAPI
          expr: sum(rate(http_requests_total{handler="/api/v1/portfolios", status=~"5.."}[5m])) / sum(rate(http_requests_total{handler="/api/v1/portfolio"}[5m])) * 100 > 5
          for: 5m
          labels:
            severity: critical
            team: backend
          annotations:
            summary: "포트폴리오 API 높은 오류율"
            description: "포트폴리오 API의 오류율이 5분 동안 5%를 초과했습니다."
  
        - alert: GitHubActionsJobFailure
          expr: github_actions_workflow_job_status{status="failure"} > 0
          for: 15m
          labels:
            severity: warning
            team: devops
          annotations:
            summary: "GitHub Actions 작업 실패"
            description: "GitHub Actions 작업 {{ $labels.job_name }}이(가) {{ $labels.workflow }} 워크플로우에서 실패했습니다. CI/CD 파이프라인을 점검하세요."
        
        - alert: TestWarning
          expr: vector(1)
          labels:
            severity: warning
          annotations:
            summary: Test warning alert
    
        - alert: TestBackend
          expr: vector(1)
          labels:
            team: backend
          annotations:
            summary: Test backend alert