apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-self-monitor
  namespace: observability
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kube-prometheus-stack-prometheus
  endpoints:
    - port: http
      interval: 30s
