apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki:3100
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"traceID":"(\w+)"'
              name: TraceID
              url: ${__value.raw}
              urlDisplayLabel: Trace
        secureJsonData:
          httpHeaderValue1: '1'
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-server
        jsonData:
          httpMethod: GET
          exemplarTraceIdDestinations:
            - name: TraceID
              datasourceUid: tempo
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo:3100
        jsonData:
          tracesToLogs:
            datasourceUid: loki
            tags: [app]
            spanEndTimeShift: 1h
            spanStartTimeShift: -1h
            filterByTraceID: true
            filterBySpanID: false
            lokiSearch: true
          serviceMap:
            datasourceUid: prometheus
          search:
            hide: false
          nodeGraph:
            enabled: true