apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki:3100
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: 'traceID=(\\w+)'
              name: TraceID
              url: ${__value.raw}
              urlDisplayLabel: View Trace in Tempo
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus:9090
        jsonData:
          httpMethod: GET
          exemplarTraceIdDestinations:
            - name: TraceID
              datasourceUid: tempo
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo:3100
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: loki
            spanStartTimeShift: "1h"
            spanEndTimeShift: "1h"
            tags: ['instance', 'job', 'namespace', 'pod']
            filterByTraceID: false
            filterBySpanID: false
            lokiSearch: true
          search:
            hide: false
          nodeGraph:
            enabled: true
          lokiSearch:
            enabled: true