apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - issuer.yaml
  - certificate.yaml
  - https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml

patches:
    - target:
        kind: Deployment
        name: opentelemetry-operator-controller-manager
      patch: |-
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --enable-cert-manager=true