apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: log-collector
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      filelog:
        include: [ /var/log/containers/*.log ]
        operators:
          - type: json_parser
          - type: regex_parser
            regex: '^(?P<time>\S+) (?P<stream>stdout|stderr) (?P<logtag>\w) (?P<log>.*)$'
            timestamp:
              parse_from: time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      loki:
        protocols:
          http:{}
    
    processors:
      k8sattributes:
        passthrough: false
        extract: 
          metadata: 
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
            - k8s.cluster.uid
        pod_association:
          - sources:
            - from: resource_attributes
              name: k8s.pod.name
            - from: resource_attributes
              name: k8s.namespace.name
      resource:
        attributes:
          - action: insert
            key: loki.format
            value: raw
          - action: insert
            key: service.name
            from_attribute: k8s.deployment.name
          - action: insert
            key: service.name
            from_attribute: k8s.daemonset.name
          - action: insert
            key: service.name
            from_attribute: k8s.statefulset.name
          - action: insert
            key: loki.resource.labels
            value:
              - k8s.container.name
              - k8s.namespace.name
              - k8s.pod.name
              - service.name
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    
    exporters:
      logging:
        loglevel: debug
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
    
    service:
      pipelines:
        logs:
          exporters:
          - loki
          processors:
          - k8sattributes
          - resource
          - memory_limiter
          - batch
          receivers:
          - loki
          - filelog