promtail:
  # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
  serviceMonitor:
    enabled: true
  config:
    snippets:
      pipelineStages:
        # not cri, because we're running in minikube with docker runtime
        - docker: {}
    clients:
      - url: http://loki.loki:3100/loki/api/v1/push
tolerations: ##  적용된 테인트에 상관없이 모든 노드에 스케쥴 될 수 있음 -> 모든 부분에서 로그 수집
  - effect: NoSchedule
    operator: Exists