apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfogram-server.fullname" . }}
  labels:
    {{- include "portfogram-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: http-management
      port: 8081
      targetPort: http-management
      protocol: TCP
  selector:
    {{- include "portfogram-server.selectorLabels" . | nindent 4 }}
