apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8889"
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.80.0
          command:
            - "/otelcol-contrib"
            - "--config=/conf/otel-collector-config.yaml"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 8889
              name: metrics
          env:
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "10000"
            - name: OTEL_METRICS_EXPORTER
              value: "prometheus"
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-config