apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
spec:
  project: default
  source:
    repoURL: https://github.com/grafana/helm-charts
    targetRevision: 6.4.0
    chart: promtail
    helm:
      valueFiles:
        - helm/promtail/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: promtail
  syncPolicy:
    automated: {}
