apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
spec:
  destination:
    name: ''
    namespace: promtail
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/promtail
    repoURL: 'https://github.com/minina0407/portfogram-mainfest.git'
    targetRevision: HEAD
    helm:
      valueFiles: []
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
