kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      volumeClaimTemplates:
        - metadata:
            name: prometheus-storage
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  grafana:
    enabled: false

ingress:
  enabled: true
  name: ingress-grafana
  class: nginx
  clusterIssuer: letsencrypt-prod
  hosts: grafana-prod.ingress.minimeisme.com
  tlsSecret: grafana-tls
  path: /
  serviceName: portfogram-monitoring-grafana
  servicePort: 3000
