image:
  tag: "51f0ceb"

tolerations:
  - key: "node"
    operator: "Equal"
    value: "worker1"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nodename
              operator: In
              values:
                - worker1
