helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: observability
    valuesFile: values.yaml
    version: 6.5.2
    includeCRDs: true

helmGlobals:
  chartHome: charts