loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory
  storage:
    type: filesystem
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

persistence:
  enabled: true
  size: 10Gi
  storageClassName: standard-rwo
