loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory
  tracing:
    enabled: true
    otlp:
      endpoint: tempo.observability.svc.cluster.local:4317
      insecure: true
  derived_fields:
    - name: traceID
      matcher: 'traceID=(\w+)'
      source: message
  storage:
    type: filesystem
  storageConfig:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

singleBinary:
  replicas: 1

# Explicitly disable all scalable components
read:
  enabled: false
write:
  enabled: false
backend:
  enabled: false
gateway:
  enabled: false

persistence:
  enabled: true
  size: 10Gi
  storageClassName: standard-rwo

# Set deployment mode to single binary
global:
  deploymentMode: "SingleBinary"

serviceMonitor:
  enabled: true

config:
  ruler:
    storage:
      type: local
      local:
        directory: /rules
  limits_config:
    max_concurrent_queries: 32