loki:
  auth_enabled: false
  configMap:
    create: true
    content: |
      auth_enabled: false
      server:
        http_listen_port: 3100
      common:
        path_prefix: /var/loki
        storage:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/boltdb-shipper-active
          cache_location: /var/loki/boltdb-shipper-cache
          shared_store: filesystem
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
      compactor:
        working_directory: /var/loki/compactor
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      query_range:
        align_queries_with_step: true
        max_retries: 5
        cache_results: true
        results_cache:
          cache:
            embedded_cache:
              enabled: true
              max_size_mb: 100

singleBinary:
  replicas: 1

serviceAccount:
  create: true
  name: loki
  annotations: {}

persistence:
  enabled: true
  size: 10Gi
  storageClassName: standard-rwo

gateway:
  enabled: false


test:
  enabled: false