apiVersion: v1
kind: Service
metadata:
  name: thanos-query
spec:
  selector:
    app: thanos-query
  ports:
    - name: http
      port: 9090
      targetPort: http
    - name: grpc
      port: 10901
      targetPort: grpc
