apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    name: ''
    namespace: kube-prometheus-stack
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/kube-prometheus-stack
    repoURL: 'https://github.com/prometheus-community/helm-charts'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: {}
