apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-staging-db-prometheus-staging-1
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  storageClassName: standard
  volumeName: prometheus-staging-db-prometheus-staging-1-pv