apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-staging-db-prometheus-staging-1-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data