redis:
  usePassword: true
  primary:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 8Gi
  sentinel:
    enabled: false
  master:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 8Gi
  metrics:
    enabled: false
  auth:
    enabled: false
  extraEnv: |
    - name: spring_redis_host
      value: "redis"
    - name: spring_redis_port
      value: "6379"
    - name: spring_cache_type
      value: "redis"
  extraEnvSecrets: |
    - name: spring_redis_password
      valueFrom:
        secretKeyRef:
          name: redis-password
          key: password

