tempo:
  serviceMonitor:
    enabled: true
  tolerations:
    - key: "node"
      operator: "Equal"
      value: "worker-2"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodename
                operator: In
                values:
                  - worker2
