apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
spec:
  destination:
    name: ''
    namespace: tempo
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/tempo
    repoURL: 'https://github.com/minina0407/portfogram-mainfest.git'
    targetRevision: HEAD
  sources: []
  project: default
