name: UpdateManifestRepository

on:
  repository_dispatch:
    types: [update-manifest]

env:
  DOCKER_REGISTRY: docker.io

jobs:
  update_manifest_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code (App Repository)
        uses: actions/checkout@v2
        with:
          repository: minina0407/PortfoGram-k8s
          ref: main
          token: ${{ secrets.APP_REPO_TOKEN }}

      - name: Configure Git credentials (App Repository)
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

      - name: Extract commit hash from App Repository
        id: extract_data_app_repo
        run: |
          COMMIT_HASH_APP_REPO=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH_APP_REPO=$COMMIT_HASH_APP_REPO" >> $GITHUB_ENV

      - name: Check out code (Manifest Repository)
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Configure Git credentials (Manifest Repository)
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

      - name: Update image tags in values-prod.yaml
        run: |
          sed -i "s#tag: \".*\"#tag: \"${COMMIT_HASH_APP_REPO}\"#g" apps/spring-boot/values-prod.yaml

      - name: Commit and push changes
        run: |
          git add apps/spring-boot/values-prod.yaml
          git commit -m "Update image tag to $COMMIT_HASH_APP_REPO"
          git push -u origin main
