name: UpdateManifestRepository

on:
  repository_dispatch:
    types: [update-manifest]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_REPO: ${{ github.event.client_payload.image_tag }}

jobs:
  update_manifest_repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git credentials
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.ACCESS_TOKEN }}@github.com" > ~/credentials

      - name: Configure Git user
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

      - name: Update image tags in all templates
        run: |
          find helm/spring-boot -type f -name 'values.yaml' -exec sed -i 's#latest#${{ github.event.client_payload.image_tag }}#g' {} \  ;
      
    





